language: objective-c
script:
  - xctool -project Ortelius.xcodeproj -scheme Ortelius-iOS -sdk iphonesimulator clean build test
  - xctool -project Ortelius.xcodeproj -scheme Ortelius clean build test
